In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [4]:
dt_default = DecisionTreeClassifier()
dt_default.fit(X_train, y_train)

y_pred_default = dt_default.predict(X_test)

print("Accuracy (Default):", accuracy_score(y_test, y_pred_default))

Accuracy (Default): 1.0


In [6]:
dt_depth3 = DecisionTreeClassifier(max_depth=3)
dt_depth3.fit(X_train, y_train)

y_pred_depth3 = dt_depth3.predict(X_test)

print("Accuracy (Max Depth = 3):", accuracy_score(y_test, y_pred_depth3))

Accuracy (Max Depth = 3): 1.0


In [7]:
dt_entropy = DecisionTreeClassifier(criterion="entropy")
dt_entropy.fit(X_train, y_train)

y_pred_entropy = dt_entropy.predict(X_test)

print("Accuracy (Entropy):", accuracy_score(y_test, y_pred_entropy))

Accuracy (Entropy): 1.0


In [8]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_entropy))

print("\nClassification Report:\n",
      classification_report(y_test, y_pred_entropy))

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

